const Search = [
  {
    src: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Tower Street Apartment",
    distance: "500m from town",
    sub: "Studio Apartment with fully furnish",
    feature: "Harga Jual: Rp. 4,5 M s/d 5 M (tipe 3BR)",
    cancel: "Free Cancellation or Reschedule",
    cancelDetail: "You can Cancel later, Booking now!",
    siStar: "8.9",
    siRate: "Very Good",
    price: "Rp. 30 juta x 12 bulan",
    tax: "Include taxes and fees",
    btn: "See Availibility",
  },
  {
    src: "https://i.pinimg.com/236x/59/ce/d0/59ced0179bed07b0c0d3b6fdbc03a1d8.jpg",
    title: " Apartemen  Sky Garden",
    distance: "1500m from town",
    sub: "Studio Apartment with fully furnish",
    feature: "Harga Jual: Rp. 5 M s/d 5,5 M (tipe 3BR)",
    cancel: "Free Cancellation or Reschedule",
    cancelDetail: "You can Cancel later, Booking now!",
    siStar: "8.9",
    siRate: "Very Good",
    price: "Rp. 24,3 juta x 12 bulan",
    tax: "Include taxes and fees",
    btn: "See Availibility",
  },

  {
    src: "https://i.pinimg.com/236x/61/f7/05/61f70541f62cf0f87c0d015a5c94c91e.jpg",
    title: "Apartemen L’avenue",
    distance: "900m from town",
    sub: "Studio Apartment with fully furnish",
    feature: "Harga Jual: Rp. 5,5 M s/d 6,5 M (tipe 3BR)",
    cancel: "Free Cancellation or Reschedule",
    cancelDetail: "You can Cancel later, Booking now!",
    siStar: "8.9",
    siRate: "Very Good",
    price: "Rp. 33,1 juta x 12 bulan",
    tax: "Include taxes and fees",
    btn: "See Availibility",
  },
  {
    src: "https://i.pinimg.com/236x/dc/7d/37/dc7d3706bdc2c3e452c2823f0aa9ede5.jpg",
    title: "Pakubuwono Residence",
    distance: "200m from town",
    sub: "Studio Apartment with fully furnish",
    feature: "Harga Jual: Rp. Rp. 4,8 M (tipe 3BR)",
    cancel: "Free Cancellation or Reschedule",
    cancelDetail: "You can Cancel later, Booking now!",
    siStar: "8.9",
    siRate: "Very Good",
    price: "25 juta x 12 bulan",
    tax: "Include taxes and fees",
    btn: "See Availibility",
  },
  {
    src: "https://i.pinimg.com/236x/4e/bf/61/4ebf61c8743198419d0c407ea93dbe80.jpg",
    title: "Apartemen Casa Grande",
    distance: "1000m from town",
    sub: "Studio Apartment with fully furnish",
    feature: "Harga Jual: Rp. 6,3 M s/d 6,5 M (tipe 3BR fully furnished)",
    cancel: "Free Cancellation or Reschedule",
    cancelDetail: "You can Cancel later, Booking now!",
    siStar: "8.9",
    siRate: "Very Good",
    price: "Rp. 47,3 juta x 12 bulan",
    tax: "Include taxes and fees",
    btn: "See Availibility",
  },
];
export default Search;
